kind: PersistentVolume
apiVersion: v1
metadata:
  name: aws-pv
  labels:
    kubernetes.io/cluster-service: "true"
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-75db11c0
    fsType: ext4
