kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aws-pvc
  labels:
    kubernetes.io/cluster-service: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
