---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: show-depl
  labels:
    type: show-type
spec:
  replicas: 3
  template:
    metadata:
      labels:
        type: show-type
    spec:
      containers:
      - name: show-container
        image: 185711092606.dkr.ecr.us-west-2.amazonaws.com/cpa/aml_k8s-env_front:v8
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            httpHeaders:
              - name: X-Custom-Header
                value: Awesome
          initialDelaySeconds: 15
          timeoutSeconds: 1
        ports:
        - containerPort: 8080
          protocol: TCP
        lifecycle:
          preStop:
            httpGet:
                path: /prestop
                port: 8080
        env:
        - name: USER_VAR
          value: important information
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        volumeMounts:
        - name: aws-store
          mountPath: /var/lib/data/aws
      volumes:
      - name: aws-store
        persistentVolumeClaim:
          claimName: aws-pvc

