---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: show-depl
  labels:
    type: show-type
spec:
  replicas: 3
  template:
    metadata:
      labels:
        type: show-type
    spec:
      containers:
      - name: show-container
        image: 185711092606.dkr.ecr.us-west-2.amazonaws.com/cpa/aml_k8s-env_front:v4
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: USER_VAR
          value: important information
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

